# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        # node-version: [18.x, 20.x, 22.x]
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: ${{ matrix.node-version }}
    - run: npm init --force --yes
    - run: npm install
    - run: npm run build --if-present
    # - run: npm test
    - uses: actions/upload-artifact@main
      with:
        name: webpack artifacts
        # path: my-server.js
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@main
      with:
        name: webpack artifacts
        # path: my-server.js
    - run: echo $(ls -la)
